name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .

    - name: Run app (test)
      run: |
        python /workspaces/upchat.github.io/app.py &
        sleep 5
        curl -f http://127.0.0.1:5000/
